PORT="${PORT:-8081}"
export ENABLE_LOGIN_FORM=True
export ENABLE_SIGNUP=False
export ENABLE_OAUTH_SIGNUP=True

export USER_PERMISSIONS_CHAT_EDIT=False
export USER_PERMISSIONS_CHAT_CONTROLS=False
export USER_PERMISSIONS_CHAT_FILE_UPLOAD=False
export USER_PERMISSIONS_CHAT_TEMPORARY=False
export USER_PERMISSIONS_FEATURES_WEB_SEARCH=False
export USER_PERMISSIONS_FEATURES_IMAGE_GENERATION=False
export USER_PERMISSIONS_FEATURES_CODE_INTERPRETER=False

export DEFAULT_USER_ROLE="user"
export VRUC_CLIENT_ID="67bf09c390f4d1021d973a5f.apps"
export VRUC_CLIENT_SECRET="_YACLMVER7qa_PD7QmHj0X7bRyMjx-iNHsyiJdN8w8s"
export VRUC_AUTH_HOST="https://v.ruc.edu.cn"
uvicorn open_webui.main:app --port $PORT --host 0.0.0.0 --forwarded-allow-ips '*' --reload